### PR TITLE
docs: Add log statement customization for debugprint.nvim

### PR DESCRIPTION
**Pull request by andrewferrier**
It's not quite right that debugprint doesn't support log statement customization - you can customize the addition/removal of each section - see the various `display_*` options, which can be set both globally and per-filetype.

### CODE REVIEW

**Comment by chrisgrieser** [comment]
Ah thanks, have only seen "Completely customizable log lines" with an X in your table and apparently misunderstood.

**Comment by andrewferrier** [comment]
No worries :)

**Comment by andrewferrier** [comment]
@chrisgrieser hijacking this thread slightly (!) to ask; what is the `nvim-lua` filetype you are handling [here](https://github.com/chrisgrieser/nvim-chainsaw/blob/c188a7d5ea7aacc2e91ffc5e2b938f2a3d5601a9/lua/chainsaw/config/log-statements-data.lua#L123)? I mean, I get it's for NeoVim-flavoured lua, but what plugin or config is setting that as the filetype? I don't think it's standard NeoVim behaviour?

**Comment by chrisgrieser** [comment]
Yeah, it's no real filetype – chainsaw uses [a really simple heuristic](https://github.com/chrisgrieser/nvim-chainsaw/blob/1e77ca5b3d798bf29c8dca4489f8ce6de512dc01/lua/chainsaw/utils.lua#L19-L23) to determine if we are in an nvim project or config, and switches to `nvim_lua` log statements then. This is since the nvim API offers stuff like `vim.inspect` or `vim.notify` which are just preferable to bare lua's `print`. 

So when you are in an nvim lua file, you use those "improved" log statements, while in other lua files (e.g. your hammerspoon or wezterm config), the pllugin will use the regular lua functions.

**Comment by andrewferrier** [comment]
Cool, thanks for explaining. I wanted to handle something similar at some stage, so I was just curious how you'd done it. Thanks!

**Pull request merged**
